"""created auth_token table

Revision ID: 0317549e3cc5
Revises: ac9c82c99a0b
Create Date: 2026-09-26 16:30:56.626872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0317549e3cc5'
down_revision: Union[str, Sequence[str], None] = 'ac9c82c99a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_webhook_created'), table_name='deliveries')
    op.create_index('ix_deliveries_webhook_created', 'deliveries', ['webhook_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deliveries_webhook_created', table_name='deliveries')
    op.create_index(op.f('ix_deliveries_webhook_created'), 'deliveries', ['status', 'next_attempt_at'], unique=False)
    # ### end Alembic commands ###
