"""added auditlog table

Revision ID: c4fd83b11e4f
Revises: c2fa68289b57
Create Date: 2026-09-26 16:32:16.690959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fd83b11e4f'
down_revision: Union[str, Sequence[str], None] = 'c2fa68289b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_webhook_created'), table_name='deliveries')
    op.create_index('ix_deliveries_webhook_created', 'deliveries', ['status', 'next_attempt_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deliveries_webhook_created', table_name='deliveries')
    op.create_index(op.f('ix_deliveries_webhook_created'), 'deliveries', ['webhook_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
